
// This file has been generated by the GUI designer. Do not modify.
namespace XamarinStudioGradleExtension
{
	public partial class GradleOptionsWidget
	{
		private global::Gtk.Frame generalFrame;
		
		private global::Gtk.Alignment GtkAlignment4;
		
		private global::Gtk.VBox vbox2;
		
		private global::Gtk.CheckButton useGradleCheckBox;
		
		private global::Gtk.Label GtkLabel4;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget XamarinStudioGradleExtension.GradleOptionsWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "XamarinStudioGradleExtension.GradleOptionsWidget";
			// Container child XamarinStudioGradleExtension.GradleOptionsWidget.Gtk.Container+ContainerChild
			this.generalFrame = new global::Gtk.Frame ();
			this.generalFrame.Name = "generalFrame";
			this.generalFrame.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child generalFrame.Gtk.Container+ContainerChild
			this.GtkAlignment4 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment4.Name = "GtkAlignment4";
			this.GtkAlignment4.LeftPadding = ((uint)(12));
			this.GtkAlignment4.TopPadding = ((uint)(6));
			// Container child GtkAlignment4.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.useGradleCheckBox = new global::Gtk.CheckButton ();
			this.useGradleCheckBox.CanFocus = true;
			this.useGradleCheckBox.Name = "useGradleCheckBox";
			this.useGradleCheckBox.Label = global::Mono.Unix.Catalog.GetString ("Use Gradle");
			this.useGradleCheckBox.DrawIndicator = true;
			this.useGradleCheckBox.UseUnderline = true;
			this.vbox2.Add (this.useGradleCheckBox);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.useGradleCheckBox]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			this.GtkAlignment4.Add (this.vbox2);
			this.generalFrame.Add (this.GtkAlignment4);
			this.GtkLabel4 = new global::Gtk.Label ();
			this.GtkLabel4.Name = "GtkLabel4";
			this.GtkLabel4.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>General</b>");
			this.GtkLabel4.UseMarkup = true;
			this.generalFrame.LabelWidget = this.GtkLabel4;
			this.Add (this.generalFrame);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
