
// This file has been generated by the GUI designer. Do not modify.
namespace XamarinStudioGradleExtension
{
	public partial class ConfigurationOptionsWidget
	{
		private global::Gtk.Frame configFrame;
		
		private global::Gtk.Alignment GtkAlignment2;
		
		private global::Gtk.Table table2;
		
		private global::Gtk.Entry fetchTargetEntry;
		
		private global::Gtk.Label label3;
		
		private global::Gtk.Label GtkLabel2;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget XamarinStudioGradleExtension.ConfigurationOptionsWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "XamarinStudioGradleExtension.ConfigurationOptionsWidget";
			// Container child XamarinStudioGradleExtension.ConfigurationOptionsWidget.Gtk.Container+ContainerChild
			this.configFrame = new global::Gtk.Frame ();
			this.configFrame.Name = "configFrame";
			this.configFrame.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child configFrame.Gtk.Container+ContainerChild
			this.GtkAlignment2 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment2.Name = "GtkAlignment2";
			this.GtkAlignment2.LeftPadding = ((uint)(12));
			this.GtkAlignment2.TopPadding = ((uint)(6));
			// Container child GtkAlignment2.Gtk.Container+ContainerChild
			this.table2 = new global::Gtk.Table (((uint)(1)), ((uint)(2)), false);
			this.table2.Name = "table2";
			this.table2.RowSpacing = ((uint)(6));
			this.table2.ColumnSpacing = ((uint)(6));
			// Container child table2.Gtk.Table+TableChild
			this.fetchTargetEntry = new global::Gtk.Entry ();
			this.fetchTargetEntry.CanFocus = true;
			this.fetchTargetEntry.Name = "fetchTargetEntry";
			this.fetchTargetEntry.IsEditable = true;
			this.fetchTargetEntry.InvisibleChar = '●';
			this.table2.Add (this.fetchTargetEntry);
			global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.table2 [this.fetchTargetEntry]));
			w1.LeftAttach = ((uint)(1));
			w1.RightAttach = ((uint)(2));
			w1.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Fetch Dependencies");
			this.table2.Add (this.label3);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table2 [this.label3]));
			w2.XOptions = ((global::Gtk.AttachOptions)(4));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			this.GtkAlignment2.Add (this.table2);
			this.configFrame.Add (this.GtkAlignment2);
			this.GtkLabel2 = new global::Gtk.Label ();
			this.GtkLabel2.Name = "GtkLabel2";
			this.GtkLabel2.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Targets</b>");
			this.GtkLabel2.UseMarkup = true;
			this.configFrame.LabelWidget = this.GtkLabel2;
			this.Add (this.configFrame);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
