
// This file has been generated by the GUI designer. Do not modify.
namespace XamarinStudioGradleExtension
{
	public partial class ProjectOptionsWidget
	{
		private global::Gtk.VBox vbox4;
		
		private global::Gtk.Frame projectTargetsFrame;
		
		private global::Gtk.Alignment GtkAlignment3;
		
		private global::Gtk.Table table3;
		
		private global::Gtk.Label label5;
		
		private global::Gtk.Label label6;
		
		private global::Gtk.Entry publishLocalTargetEntry;
		
		private global::Gtk.Entry publishTargetEntry;
		
		private global::Gtk.Label GtkLabel3;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget XamarinStudioGradleExtension.ProjectOptionsWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "XamarinStudioGradleExtension.ProjectOptionsWidget";
			// Container child XamarinStudioGradleExtension.ProjectOptionsWidget.Gtk.Container+ContainerChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 18;
			this.vbox4.BorderWidth = ((uint)(2));
			// Container child vbox4.Gtk.Box+BoxChild
			this.projectTargetsFrame = new global::Gtk.Frame ();
			this.projectTargetsFrame.Name = "projectTargetsFrame";
			this.projectTargetsFrame.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child projectTargetsFrame.Gtk.Container+ContainerChild
			this.GtkAlignment3 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment3.Name = "GtkAlignment3";
			this.GtkAlignment3.LeftPadding = ((uint)(12));
			this.GtkAlignment3.TopPadding = ((uint)(12));
			// Container child GtkAlignment3.Gtk.Container+ContainerChild
			this.table3 = new global::Gtk.Table (((uint)(2)), ((uint)(2)), false);
			this.table3.Name = "table3";
			this.table3.RowSpacing = ((uint)(6));
			this.table3.ColumnSpacing = ((uint)(6));
			// Container child table3.Gtk.Table+TableChild
			this.label5 = new global::Gtk.Label ();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Publish Local");
			this.table3.Add (this.label5);
			global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.table3 [this.label5]));
			w1.XOptions = ((global::Gtk.AttachOptions)(4));
			w1.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.label6 = new global::Gtk.Label ();
			this.label6.Name = "label6";
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("Publish");
			this.table3.Add (this.label6);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table3 [this.label6]));
			w2.TopAttach = ((uint)(1));
			w2.BottomAttach = ((uint)(2));
			w2.XOptions = ((global::Gtk.AttachOptions)(4));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.publishLocalTargetEntry = new global::Gtk.Entry ();
			this.publishLocalTargetEntry.CanFocus = true;
			this.publishLocalTargetEntry.Name = "publishLocalTargetEntry";
			this.publishLocalTargetEntry.IsEditable = true;
			this.publishLocalTargetEntry.InvisibleChar = '●';
			this.table3.Add (this.publishLocalTargetEntry);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table3 [this.publishLocalTargetEntry]));
			w3.LeftAttach = ((uint)(1));
			w3.RightAttach = ((uint)(2));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.publishTargetEntry = new global::Gtk.Entry ();
			this.publishTargetEntry.CanFocus = true;
			this.publishTargetEntry.Name = "publishTargetEntry";
			this.publishTargetEntry.IsEditable = true;
			this.publishTargetEntry.InvisibleChar = '●';
			this.table3.Add (this.publishTargetEntry);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table3 [this.publishTargetEntry]));
			w4.TopAttach = ((uint)(1));
			w4.BottomAttach = ((uint)(2));
			w4.LeftAttach = ((uint)(1));
			w4.RightAttach = ((uint)(2));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			this.GtkAlignment3.Add (this.table3);
			this.projectTargetsFrame.Add (this.GtkAlignment3);
			this.GtkLabel3 = new global::Gtk.Label ();
			this.GtkLabel3.Name = "GtkLabel3";
			this.GtkLabel3.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Targets</b>");
			this.GtkLabel3.UseMarkup = true;
			this.projectTargetsFrame.LabelWidget = this.GtkLabel3;
			this.vbox4.Add (this.projectTargetsFrame);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.projectTargetsFrame]));
			w7.Position = 0;
			w7.Expand = false;
			w7.Fill = false;
			this.Add (this.vbox4);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
